### ISSUE TITLE
LUA Error since TWW pre patch

### ISSUE THREAD

**Issue by Xzatly** [ReubinAuthor/ClassicPlatesPlus#10]
Thanks for this great addon, using it on Classic and Retail.

Since TWW pre patch on Retail I have LUA Errors (2):

`Message: Interface/AddOns/ClassicPlatesPlus/settings.lua:1032: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
Time: Tue Aug 20 16:07:14 2024
Count: 1
Stack: Interface/AddOns/ClassicPlatesPlus/settings.lua:1032: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@Interface/AddOns/ClassicPlatesPlus/settings.lua"]:1032: in function `Load_Settings'
[string "@Interface/AddOns/ClassicPlatesPlus/init.lua"]:20: in function <Interface/AddOns/ClassicPlatesPlus/init.lua:11>

Locals: self = <table> {
}
panelMain = Frame {
 divider = Texture {
 }
 scrollChild = Frame {
 }
 resetSettings = Button {
 }
 title = FontString {
 }
 list = <table> {
 }
 name = "ClassicPlatesPlus"
 header = Frame {
 }
 icon = Texture {
 }
 scrollFrame = ScrollFrame {
 }
}
(for state) = <table> {
 1 = Frame {
 }
 2 = Frame {
 }
 3 = Frame {
 }
 4 = Frame {
 }
}
(for control) = 1
k = 1
v = Frame {
 divider = Texture {
 }
 scrollChild = Frame {
 }
 resetSettings = Button {
 }
 title = FontString {
 }
 list = <table> {
 }
 name = "ClassicPlatesPlus"
 header = Frame {
 }
 icon = Texture {
 }
 scrollFrame = ScrollFrame {
 }
}
(*temporary) = nil
(*temporary) = Frame {
 divider = Texture {
 }
 scrollChild = Frame {
 }
 resetSettings = Button {
 }
 title = FontString {
 }
 list = <table> {
 }
 name = "ClassicPlatesPlus"
 header = Frame {
 }
 icon = Texture {
 }
 scrollFrame = ScrollFrame {
 }
}
(*temporary) = "attempt to call global 'InterfaceOptions_AddCategory' (a nil value)"
func = <table> {
}
myAddon = "ClassicPlatesPlus"
white = ""
purple = ""
green = ""
blue = ""
orange = ""
data = <table> {
 tanks = <table> {
 }
 tickers = <table> {
 }
 isRetail = true
 members = <table> {
 }
 myTarget = <table> {
 }
 classBarHeight = 0
 settings = <table> {
 }
 colors = <table> {
 }
 isClassic = false
 nameplates = <table> {
 }
 hooks = <table> {
 }
 cvars = <table> {
 }
 isCata = false
}
yellow = ""
`

`Message: Interface/AddOns/ClassicPlatesPlus/auras.lua:56: attempt to call upvalue 'UnitAura' (a nil value)
Time: Tue Aug 20 16:07:34 2024
Count: 2
Stack: Interface/AddOns/ClassicPlatesPlus/auras.lua:56: attempt to call upvalue 'UnitAura' (a nil value)
[string "@Interface/AddOns/ClassicPlatesPlus/auras.lua"]:56: in function `createFrames'
[string "@Interface/AddOns/ClassicPlatesPlus/auras.lua"]:374: in function `Update_Auras'
[string "@Interface/AddOns/ClassicPlatesPlus/init.lua"]:156: in function <Interface/AddOns/ClassicPlatesPlus/init.lua:11>

Locals: filter = "HELPFUL"
auraType = "buffs"
r = 0
g = 1
b = 0
(for index) = 1
(for limit) = 40
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = "player"
(*temporary) = 1
(*temporary) = "HELPFUL"
(*temporary) = "attempt to call upvalue 'UnitAura' (a nil value)"
UnitAura = nil
unit = "player"
canAttack = false
data = <table> {
 nameplate = ClassicPlatesPlusnameplateSelf {
 }
 tanks = <table> {
 }
 tickers = <table> {
 }
 isRetail = true
 members = <table> {
 }
 myTarget = <table> {
 }
 classBarHeight = 0
 settings = <table> {
 }
 colors = <table> {
 }
 isClassic = false
 nameplates = <table> {
 }
 hooks = <table> {
 }
 cvars = <table> {
 }
 isCata = false
}
AurasHidePassive = 1
AurasShow = 1
unitFrame = ClassicPlatesPlusnameplateSelf {
 debuffs = <table> {
 }
 buffsCounter = FontString {
 }
 powerbar = StatusBar {
 }
 sorted = <table> {
 }
 border = Texture {
 }
 powerbarSpark = Texture {
 }
 toSort = <table> {
 }
 buffs = <table> {
 }
 healthSecondary = FontString {
 }
 healthbarSpark = Texture {
 }
 healthbarBackground = Texture {
 }
 raid = <table> {
 }
 animationShow = AnimationGroup {
 }
 extraBar = StatusBar {
 }
 powerbarBackground = Texture {
 }
 classPower = Frame {
 }
 healthbar = StatusBar {
 }
 power = FontString {
 }
 animationHide = AnimationGroup {
 }
 healPrediction = Texture {
 }
 powerbarCostSpark = Texture {
 }
 powerbarCost = Texture {
 }
 powerTotal = FontString {
 }
 powerMain = FontString {
 }
 main = Frame {
 }
 debuffsCounter = FontString {
 }
 unit = "player"
 healPredictionSpark = Texture {
 }
 healthTotal = FontString {
 }
 healthMain = FontString {
 }
}
scale = 0.850000
func = <table> {
}
`

Thanks

**Comment by Xzatly** [comment]
Forgot to mention, option panel is also missing now.

**Comment by marcogruebler** [comment]
same, would love to see this updated

**Comment by fregattenfahrer** [comment]
Same here - not working the way it is intended :)... Would like to see updates here...
