### ISSUE TITLE
LUA Error：attempt to call global 'GetSpellInfo' (a nil value)

### ISSUE THREAD

**Issue by class2u** [ReubinAuthor/ClassicPlatesPlus#13]
Thank you for making this great addon. I get the following error message when I adding spell ID to blacklist. WoW version is 11.0.5 and addon version is v3.3.4.

1x ...faceClassicPlatesPlus/settings_functions.lua:1119: attempt to call global 'GetSpellInfo' (a nil value)
[string "@ClassicPlatesPlus/settings_functions.lua"]:1119: in function <...faceClassicPlatesPlus/settings_functions.lua:1118>
[string "@ClassicPlatesPlus/settings_functions.lua"]:1352: in function <...faceClassicPlatesPlus/settings_functions.lua:1351>

Locals:
list = <table> {
}
input = "455020"
(*temporary) = nil
(*temporary) = "455020"
(*temporary) = "attempt to call global 'GetSpellInfo' (a nil value)"

**Comment by ReubinAuthor** [comment]
Fixed it! Thank you very much for reporting it, much appreciated!
