### ISSUE TITLE
Error when clicking the player untiframe

### ISSUE THREAD

**Issue by class2u** [ReubinAuthor/ClassicPlatesPlus#14]
I get the following error message when clicking the player untiframe after reloading ui. ClassicPlates Plus version is v3.3.7

2x ClassicPlatesPlus/core.lua:437: attempt to index field 'auras' (a nil value)
[string "@ClassicPlatesPlus/core.lua"]:437: in function `InteractIcon'
[string "@ClassicPlatesPlus/core.lua"]:275: in function `myTarget'
[string "@ClassicPlatesPlus/init.lua"]:60: in function <ClassicPlatesPlus/init.lua:11>
[string "=[C]"]: in function `TargetUnit'
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:500: in function `handler'
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:667: in function <...ddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:649>
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:681: in function <...ddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:674>
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:756: in function <...ddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:741>

Locals:
self = <table> {
}
nameplate = NamePlate1 {
 driverFrame = NamePlateDriverFrame {
 }
 namePlateUnitToken = "nameplate1"
 UnitFrame = Button {
 }
 unitFrame = Frame {
 }
 template = "NamePlateUnitFrameTemplate"
}
unitFrame = Frame {
 guild = FontString {
 }
 powerbar = Frame {
 }
 pvp_flag = Texture {
 }
 healthSecondary = FontString {
 }
 level = Frame {
 }
 quest = Texture {
 }
 raidTarget = Frame {
 }
 classification = Texture {
 }
 healthbar = StatusBar {
 }
 castbar = Frame {
 }
 threatPercentage = Frame {
 }
 healthMain = FontString {
 }
 fellowshipBadge = Frame {
 }
 buffsCounter = FontString {
 }
 name = FontString {
 }
 debuffsCounter = FontString {
 }
 highlightsStrata = Frame {
 }
 classPower = Frame {
 }
 portrait = Frame {
 }
 parent = Frame {
 }
}
interactIcon = Texture {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'auras' (a nil value)"
data = <table> {
 nameplate = ClassicPlatesPlusnameplateSelf {
 }
 tanks = <table> {
 }
 tickers = <table> {
 }
 isRetail = true
 tooltip = <table> {
 }
 members = <table> {
 }
 myTarget = <table> {
 }
 classBarHeight = 21
 settings = <table> {
 }
 colors = <table> {
 }
 isClassic = false
 nameplates = <table> {
 }
 hooks = <table> {
 }
 cvars = <table> {
 }
 isCata = false
}

**Comment by ReubinAuthor** [comment]
Hey @class2u, does it still occur on v3.3.8?

**Comment by class2u** [comment]
No error now, thank you!
