### ISSUE TITLE
Error in v.3.3.9

### ISSUE THREAD

**Issue by tanrak** [ReubinAuthor/ClassicPlatesPlus#15]
In version 3.3.9, the following error occurs if configuration files are not already present:

`53x ClassicPlatesPlus/init.lua:12: attempt to index global 'CFG_Account_ClassicPlatesPlus' (a nil value)
[string "@ClassicPlatesPlus/init.lua"]:12: in function <ClassicPlatesPlus/init.lua:11>

Locals:
self = Frame {
}
event = "ADDON_LOADED"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'CFG_Account_ClassicPlatesPlus' (a nil value)"
func = <table> {
}
myAddon = "ClassicPlatesPlus"
data = <table> {
 tanks = <table> {
 }
 tickers = <table> {
 }
 isRetail = false
 tooltip = <table> {
 }
 members = <table> {
 }
 myTarget = <table> {
 }
 classBarHeight = 0
 settings = <table> {
 }
 colors = <table> {
 }
 isClassic = true
 nameplates = <table> {
 }
 hooks = <table> {
 }
 cvars = <table> {
 }
 isCata = false
}
`

**Comment by ReubinAuthor** [comment]
Tank you very much for the report
