### ISSUE TITLE
Show dispellable buffs on nameplate

### ISSUE THREAD

**Issue by z0n** [ReubinAuthor/ClassicPlatesPlus#5]
Hi, not sure if I didn't find the option or if it's not implemented 😄  
Is it possible to show dispellable buffs on nameplates? E.g. enrage spells if I am able to dispell them.  
If it's not a feature yet, I'd like to request it 😄

**Comment by ll0752759** [comment]
you can select "show buffs on enemy", and even control how many buffs on enemy.
but the thing is : it doesn't show clearly whether these buffs can be dispelled by you. And it's not very smart to show only buffs that can be dispelled regardless of how many. so if you only choose to show one buff, it doesn't display others automatically.
And this is the reason I gave up this nameplate.

**Comment by ll0752759** [comment]
plus the buffs on enemy are not very obvious, when there are lots of mobs together. there's no blinking effects.
